# version: '3'
services:
  nginx_container:
    build: ./nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - test-network
    container_name: nginx_container

  test_container:
    build: ./test:3.9
    depends_on:
      - nginx_container
    volumes:
      - ./output:/output
    networks:
      - test-network
    container_name: test_container

networks:
    test-network:
