# version: '3'
services:
  nginx_container:
    image: ghcr.io/lilachshay98/f5_assignment/nginx_image:latest1 ./nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - test-network
    container_name: nginx_container

  test_container:
    image: ghcr.io/lilachshay98/f5_assignment/test_image:latest1 ./test
    depends_on:
      - nginx_container
    volumes:
      - ./output:/output
    networks:
      - test-network
    container_name: test_container

networks:
    test-network:
