name: Build and Test Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository   
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  
      
      # Step 3: Cache Docker layers to speed up build
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
          
      # Step 4: Build the Docker images (nginx and test)
      - name: Build Nginx Docker image
        run: |
          docker build -t nginx_image ./nginx

      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
            
      # Step 6: Run the Nginx container (test container won't be started)
      - name: Run Nginx container
        run: docker-compose up -d  

      # Step 8: Check if tests passed by inspecting the output file
      - name: Check Test Results
        run: |
          if test -f /output/succeeded; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1

      # Step 9: Upload result file (succeeded or fail) as an artifact
      - name: Upload test result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: /output 



